
language: cpp
sudo: required
dist: bionic

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated libblas-dev libboost-all-dev libfftw3-dev libgfortran3 libhdf5-serial-dev libgmp-dev liblapack-dev libopenmpi-dev libclang-dev python-clang-6.0 python-dev python-h5py python-mako python-matplotlib python-mpi4py python-numpy python-scipy python-sphinx libjs-mathjax libnfft3-dev

install: true

script:
  - export INSTALL_DIR=$HOME/root_install # We install outside the repository
  # ===== Set up TRIQS
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/TRIQS/triqs --branch unstable
  - mkdir triqs/build && cd triqs/build
  - cmake .. -DBuild_Tests=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
  - make -j2 install
  - source $INSTALL_DIR/share/triqsvars.sh
  # ===== Set up app4triqs and test
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DASAN=ON -DUBSAN=ON
  - export UBSAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
  - export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
  - export UBSAN_OPTIONS=symbolize=1:print_stacktrace=1
  - export ASAN_OPTIONS=symbolize=1:detect_leaks=0
  - export CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 && make test
